### ISSUE TITLE
Nice to have: AudioFileLoader performance improvement

### ISSUE THREAD

**Issue by w4iei** [audiolabs/webMUSHRA#101]
When loading a 100mb configuration, the main javascript thread of loading in the audio files takes a considerable amount of time (~15s) to load on safari/chrome, in comparison to 2s of network requests. 
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/3508820/188439442-a3a38c31-7efe-49f6-863a-3575e13b596f.png">

**Comment by faroit** [comment]
@w4iei Are you generating the lower anchors by webmushra? If yes, try to disable that and recheck performance. 

The anchors are filters processed in js and might be slow for large files.

**Comment by w4iei** [comment]
@faroit Thank you. This is definitely the cause of the performance issue. I will preprocess the anchors and serve them. Thank you!
