### ISSUE TITLE
PhP 8 compatible?

### ISSUE THREAD

**Issue by DrWig** [audiolabs/webMUSHRA#103]
When switching my server to PhP 8, webmushra is no longer able to write the results to the file.  Switching back to PhP 7.x and everything works fine.  It doesn't actually flag an error to the user, but there is a 500 error if looked at in Chrome's developer tools

Is there known compatibility issues with webmushra and PhP 8?

**Comment by faroit** [comment]
yes, its not compatible with php 8 afaik. Also, I highly recommend https://github.com/nils-werner/pymushra/ as an alternative backend
