### ISSUE TITLE
How to disable looping?

### ISSUE THREAD

**Issue by JulesPomme** [audiolabs/webMUSHRA#119]
Hi there.
Is there a straightforward way to disable the playback loop? I'm aware of the enableLooping parameter, but I would like to completely turn off the looping (i.e., when I hit the play button, the stimulus is played once only).
Thank you!

**Comment by RichardHanr** [comment]
Is this what you want?
enableLooping: false

**Comment by faroit** [comment]
@JulesPomme can this be closed?

**Comment by JulesPomme** [comment]
Hello, thank you for your help. To be honest, I ended up developing my own solution. But I remember that setting enableLooping to false was not a valid solution for me :/ However, from my point of view, the problem is now solved!
