### ISSUE TITLE
How to deal with so many C？

### ISSUE THREAD

**Issue by a897456** [audiolabs/webMUSHRA#129]
![image](https://github.com/user-attachments/assets/7ffc6dea-78e8-4681-8ee0-7c6cc16d84f3)
How can the C1 - C30 of stimuli be placed on one page?

**Comment by faroit** [comment]
> ![image](https://github.com/user-attachments/assets/7ffc6dea-78e8-4681-8ee0-7c6cc16d84f3)
> 
> How can the C1 - C30 of stimuli be placed on one page?

I think this is out of scope for a mushra test as it's impossible for in a normal setting to rank 30 conditions.
