### ISSUE TITLE
How to get others to participate in this survey?

### ISSUE THREAD

**Issue by a897456** [audiolabs/webMUSHRA#130]
Hi @faroit 
### On my computer, it is like this:
![1a4b56bce89876126b1545dc8d2ca28](https://github.com/user-attachments/assets/5565be1b-b991-4d5a-80c7-9e45f93a3a4a)
### On someone else's computer, it is like this:
![image](https://github.com/user-attachments/assets/dd7850f3-97f0-4f58-bef5-803fc6f2e9af)

**Comment by eminentgu** [comment]
well it is obvious that people can't connect to ur localhost address on their computer lol. So to be short u have two options, one is to rent a server, install php and run it, then people can access this form with ur server's ip address. The other one is to expose ur computer to the public internet so people can have access to ur computer with IP address, which requires u to do "Intranet Penetration".FYI
