### ISSUE TITLE
Error occurs when writing results to csv

### ISSUE THREAD

**Issue by npuichigo** [audiolabs/webMUSHRA#22]
PHP Warning:  Invalid argument supplied for foreach() in webMUSHRA/service/write.php

**Comment by npuichigo** [comment]
Undefined index: sessionJSON

**Comment by faroit** [comment]
which config were you using? which php version?

**Comment by bijulette** [comment]
Same issue on customized config. What do I need to check to solve the problem?

**Comment by faroit** [comment]
hi,

check the javascript console in your browser to see if there are some error messages. Also try to check if your yaml contains some formatting errors by running it through a [linter](http://www.yamllint.com/)

**Comment by bijulette** [comment]
Hi, thank you for your reply. It seems that there is no formatting error (check done through the linter), and this is what I get in the javascript console after completing the customized test:
![capture](https://user-images.githubusercontent.com/42345045/44036913-a5354176-9f1b-11e8-80f9-9575065941c6.PNG)

I actually also see these two warnings when running the same customized config but containing less "trials" (number of answers the subjects have to give). However, I also observed that the issue (error occurring when writing the results to csv) does not appear anymore in the case of the shorter test. Any idea?

**Comment by faroit** [comment]
does the [default.yaml](https://github.com/audiolabs/webMUSHRA/blob/master/configs/default.yaml) run in your setup (including the csv writeout)?

**Comment by faroit** [comment]
Also, if you can, post/link your config here, please

**Comment by bijulette** [comment]
default.yaml config works (including the csv writeout). My customized config (with audio contents from webMUSHRA) is below (in .txt format)

[custom_config.txt](https://github.com/audiolabs/webMUSHRA/files/2285801/custom_config.txt)

**Comment by faroit** [comment]
try removing the spaces from the `id` fields and add underscores, maybe

**Comment by bijulette** [comment]
it didn't work, any other ideas?

**Comment by faroit** [comment]
I've updated the yaml parse (see https://github.com/audiolabs/webMUSHRA/pull/29) and tested your config. it works for me and the csv writeout seems okay (see attached file).

Please test the PR branch and tell me in the discussion if this fixes your problem. 
[paired_comparison.csv.txt](https://github.com/audiolabs/webMUSHRA/files/2286447/paired_comparison.csv.txt)

**Comment by bijulette** [comment]
Unfortunately it didn't resolve the issue for me. Tried on browsers Chrome, Mozilla Firefox, and Internet Explorer. I am using Windows. Hereafter is what I see in cmd.exe when sending the results (using both PR branch suggested and master):
![capture](https://user-images.githubusercontent.com/42345045/44094993-572740e0-9fe0-11e8-91c2-7aa401dc3b40.PNG)

**Comment by faroit** [comment]
@bijulette Looks like an php issue. I can't help with windows, sorry. I recommend to try out our docker containers or switch to an older/newer version of php. The docker containers use php 7.0 I am running 7.1 on OS X (worked). If you find a bug, please let us know.

**Comment by bijulette** [comment]
Hi,
Changing for an older php version in Xampp fixed my problem (currently working php version: 7.0.31). Thank you for your help!

**Comment by faroit** [comment]
okay, what version have you used before?
