### ISSUE TITLE
How to change from mono channel to multichannel ?

### ISSUE THREAD

**Issue by npuichigo** [audiolabs/webMUSHRA#23]
It seems that all the wave played are mono, and my headset is ringing only to the left.

**Comment by aladami** [comment]
Hi Yuchao,
if you are referencing to the example audio files, you are right. These are all mono.
For multichannel playback, simply use audio files with more than one channel.
In case you want to use mono, but played back on the left and right channel of your headset/speakers, you need to provide it in double mono, meaning you create a two-channel audio file with the same content in both channels.

Best,
Alex

**Comment by npuichigo** [comment]
Thank you for your reply!
