### ISSUE TITLE
Deploy webMUSHRA on aws EC2, php installed. No result created after clicking "send results" button.

### ISSUE THREAD

**Issue by ronggong** [audiolabs/webMUSHRA#24]
Thanks for the webMUSHRA!

I deployed webMUSHRA on an aws ec2 server. Php is also installed. 

The problem happens after I finished the test and clicked "send results". No error reported, however, I can't see any folder generated in my webMUSHRA folder on the EC2 server?

This has been tested locally, which successfully created the result folder.

**Comment by faroit** [comment]
have you checked the php error logs (e.g. `/var/log/apache2/error.log` on debian) ?

**Comment by ronggong** [comment]
Thanks for the fast reply!

apache2 folder doesn't exist in my /var/log path.

However, problem solved. I have installed the old version of LAMP on the ec2, now I switched to httpd 2.4 and php 5.6. It works!

**Comment by ronggong** [comment]
update:

It still doesn't work. It worked 5 days ago after I updated the httpd and php, however, I just tried it again, it still can't transfer the results back to the folder...

I checked the error log and found these:

[Tue Dec 26 12:44:05.331260 2017] [:error] [pid 9904] [client 210.73.8.63:62082] PHP Warning:  fputcsv() expects parameter 1 to be resource, boolean given in /var/www/html/webMUSHRA/service/write.php on line 81, referer: http://ec2-13-250-5-77.ap-southeast-1.compute.amazonaws.com/webMUSHRA/?config=daxp-Wo_jia_di-Hong_deng_ji-dxjky.yaml
[Tue Dec 26 12:44:05.331264 2017] [:error] [pid 9904] [client 210.73.8.63:62082] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/html/webMUSHRA/service/write.php on line 84, referer: http://ec2-13-250-5-77.ap-southeast-1.compute.amazonaws.com/webMUSHRA/?config=daxp-Wo_jia_di-Hong_deng_ji-dxjky.yaml

**Comment by faroit** [comment]
@mschoeffler can you have a look?

**Comment by ronggong** [comment]
thanks @faroit problem solved. the result folder didn't have the write permission for the users. I did sudo chmod 775 to the results folder.
