### ISSUE TITLE
webMUSHRA doesn't work correctly on Chrome >= 70

### ISSUE THREAD

**Issue by faroit** [audiolabs/webMUSHRA#26]
Lets have this in mind and check if we are affected:
https://bugs.chromium.org/p/chromium/issues/detail?id=807017

**Comment by faroit** [comment]
version 66 is now in the Dev channel. Can someone test it using chrome 66? @mschoeffler @aladami

**Comment by faroit** [comment]
Chrome 66 was released and I just checked: webMUSHRA is affected by this change. 
In clear text: __webMUSHRA does not work anymore with Chrome!__

@mschoeffler do you have time to fix it?
If not, I would propose to either put a warning in the readme or deprecate webMUSHRA entirely.

**Comment by faroit** [comment]
@mschoeffler I've added a warning on the readme.md.

**Comment by faroit** [comment]
ping @mschoeffler

**Comment by faroit** [comment]
I don't know what exactly has changed in Chrome but it works fine now in 66.0.3359.139

**Comment by faroit** [comment]
stopped working again in Chrome 66.0.3359.170... 

@mschoeffler

**Comment by faroit** [comment]
> Note: The Web Audio API will be included in the Chrome autoplay policy with M70 (October 2018).

new autoplay policy will break webmushra again

**Comment by faroit** [comment]
> The Web Audio API will be included in the Chrome autoplay policy with M71 (December 2018).

we need to address this soon

**Comment by lgestin** [comment]
Adding 
```
document.addEventListener("click", function() {
    if (audioContext.state !== 'running') {
        audioContext.resume();
    }
}, true);
``` 

in `startup.js` fixes the issue for me.

**Comment by faroit** [comment]
@lgestin looks like a working workaround, thanks. Can you add a PR?

**Comment by faroit** [comment]
@lgestin in case this is still a recommended workaround, can you open a PR for this fix?
