### ISSUE TITLE
How to make webMUSHRA publicly available?

### ISSUE THREAD

**Issue by HusainKapadia** [audiolabs/webMUSHRA#30]
Currently when I run the command 

` docker-compose -f docker-compose.yml up`

It launches webMUSHRA, however, this is locally hosted on my laptop and I cannot access the link from another computer. How do I make it publicly available? I tried techniques like port forwarding but it did not work for docker-compose. Can you please recommend a way to do this. Thank you.

**Comment by faroit** [comment]
Can this be closed?

**Comment by HusainKapadia** [comment]
Yes, I solved it by hosting everything on an AWS EC2 instance which was then made available publicly.
