### ISSUE TITLE
Change the algorithm used for "randomized experiments"

### ISSUE THREAD

**Issue by krlln** [audiolabs/webMUSHRA#33]
Hi,
The algorithm currently used for randomly ordering the experiment pages involves providing `function() { return 0.5 - Math.random(); }` to `array.sort`.
This method is biased: it is more probable for the first page in the YAML config file to be presented in the first pages. (see https://stackoverflow.com/a/18650169)
If possible, I'd recommend using the Fisher-Yates (aka Knuth) Shuffle as recommended here: https://stackoverflow.com/a/2450976.
Regards,
Krlln 
https://github.com/audiolabs/webMUSHRA/blob/c929877e9bdc56ff5f0b26460219787e6e31537d/startup.js#L73-L75

**Comment by faroit** [comment]
Thanka for spotting this. Would you be able to provide a PR?

**Comment by krlln** [comment]
Yes I would. I'll write it tomorrow.
