### ISSUE TITLE
Audio doesn't work on 1st page

### ISSUE THREAD

**Issue by DrWig** [audiolabs/webMUSHRA#40]
The 1st page of the test doesn't have working audio.  Adding a 'welcome' page, or navigating to another page and back again fixes it, though.

**Comment by faroit** [comment]
Isn't this related to #26 ?

**Comment by DrWig** [comment]
if so, an easy fix would be a mandatory welcome page!

**Comment by faroit** [comment]
just to double check, can you please report if you use chrome and if: does it work fine on firefox?

> if so, an easy fix would be a mandatory welcome page!
I think thats too much of a hack. We should just fix #26

**Comment by DrWig** [comment]
yes, I use Chrome.  I don't have firefox installed

**Comment by DrWig** [comment]
I'll give you a couple of test links in a mo

**Comment by DrWig** [comment]
Apologies for the swearing in the audio....it's my students choice!

1 page not working in chrome:
https://brucewiggins.co.uk/testing/mush/?config=wigtest1pg.yaml

2 page which does work:
https://brucewiggins.co.uk/testing/mush/?config=wigtest2pg.yaml

**Comment by faroit** [comment]
alright, I checked the examples: it works fine in firefox and I confirm that it doesn't work in chrome. As this is a duplicate of #26, i'm closing this
