### ISSUE TITLE
configs are not very forgiving of non LF returns

### ISSUE THREAD

**Issue by DrWig** [audiolabs/webMUSHRA#41]
not sure if this is an issue you can even fix, so close/ditch if that's the case, but the config files are very unforgiving of non LF line breaks.......it took me quite a while to troubleshoot a students config to figure this out (they edited in Windows Notepad).

Perhaps mention this in the docs (i.e. not to use notepad ;-) )

p.s. WebMushra is an awesome resource, thank you!

**Comment by faroit** [comment]
this is a general issue with YAML files. Its true that we should have maybe gone with json files instead (which would require a lot more brackets instead though).

One thing we might want to recommend in the docs is to verify the config files before trying them .e.g. by using a yaml validator: http://www.yamllint.com/

Feel free to open a PR to extened the docs or readme

**Comment by DrWig** [comment]
Thanks for the tip.  I'll look at a PR, too.
