### ISSUE TITLE
Training phase and evaluation phase

### ISSUE THREAD

**Issue by actlee** [audiolabs/webMUSHRA#42]
Hi, I am so grateful for this webMUSHRA.

I was wondering whether I can have a training phase and an evaluation phase by using a single YAML configuration.

Thanks!

**Comment by faroit** [comment]
what do you mean by this exactly? You can have as many pages in one experiment as you like. See [this experiment for example](https://audiolabs.github.io/webMUSHRA/?config=complete.yaml).

**Comment by actlee** [comment]
In Section 5.2 in the recommendation, it explains about the training phase. I was wondering how I can use webMUSHRA to have a training phase and an evaluation phase. 

I was not sure I can make only a few pages out of all the pages random. For example, say, I made 10 pages, and the first 5 pages are for the training and the rest are for the evaluation. I expected the first 5 pages are randomized and the second 5 pages are randomized separately. 

I will first have a look at the example that you linked (complete.yaml).
