### ISSUE TITLE
How to set a multiline content?

### ISSUE THREAD

**Issue by kanthasamyiit** [audiolabs/webMUSHRA#43]
Hello. I want to give a bulletted instruction set to the listeners in the first page. In the 'content :' key, I am able to add a single, long line. But, not able to break it into multiple lines. I tried the yaml clipping keys '>', '|', '>-'. They didn't work. '\n' also didn't work. Is there way to add a multiline instruction?
Thanks.

**Comment by aladami** [comment]
Hi,
you can use an unsorted list to realize this, something like:
`content:  Please rate the following attributes<ul><li>Basic Audio Quality</li><li>Spatial Consistency</li><li>etc.</li></ul>`

**Comment by kanthasamyiit** [comment]
Thank you so much for the quick and simple solution! It worked!
