### ISSUE TITLE
How to set up a questionnaire between two mushra pages ? 

### ISSUE THREAD

**Issue by aurianworld** [audiolabs/webMUSHRA#44]
I'm trying to have a little questionnaire after each page of mushra test, but it seems that it can be done only for the end page. Is there a way to do that ?

**Comment by faroit** [comment]
can you post your config?

**Comment by aurianworld** [comment]
Yes here it is : 
[default.zip](https://github.com/audiolabs/webMUSHRA/files/4757651/default.zip)

**Comment by ashish10alex** [comment]
Any follow up on this ? I was in the need for to add something similar .

**Comment by faroit** [comment]
@ashish10alex @aurianworld the questionnaire is [part of the FinishPage](https://github.com/audiolabs/webMUSHRA/blob/master/lib/webmushra/pages/FinishPage.js) so currently, this is not possible. Therefore you would have to create your own custom page which includes only a questionnaire. 

As a workaround, I would suggest creating the config dynamically using https://github.com/nils-werner/pymushra that way you could just have multiple experiments in a row...
