### ISSUE TITLE
Add a logo at the bottom of each page

### ISSUE THREAD

**Issue by aurianworld** [audiolabs/webMUSHRA#46]
How can I add a logo at the bottom of each page ? Or at least of the first page of the test ?
Thanks you

**Comment by faroit** [comment]
The easiest way would probably to modify these parts of `index.html`:

https://github.com/audiolabs/webMUSHRA/blob/a815c79d6b9447c641b906a0c5fe099a4bb80cf9/index.html#L154-L156

A nicer way would be to add a custom logo path to the config files and parse this path here. We'd welcome a PR for this

**Comment by aurianworld** [comment]
Thanks you it worked well. Here is the index.html now 
[index.zip](https://github.com/audiolabs/webMUSHRA/files/4776272/index.zip)

**Comment by faroit** [comment]
Great that it works for you. If you can provide a generic solution with parsing the config file, feel free to provide a PR. Otherwise please ckodz

**Comment by aurianworld** [comment]
I'm new to github and I don't know what is a Pull request, then I prefer to close. 
Thanks for your help.
