### ISSUE TITLE
How to force rating before continuing?

### ISSUE THREAD

**Issue by evelyndjwilliams** [audiolabs/webMUSHRA#49]
Is there any setting to ensure participants rate all the audio samples before continuing to the next page?

**Comment by faroit** [comment]
I think this will be covered by #50 @jpauwels

**Comment by evelyndjwilliams** [comment]
> I think this will be covered by #50 @jpauwels

Thanks!

**Comment by jpauwels** [comment]
It's actually already possible in the current version (at least for Likert single or multiple stimulus pages) by adding `mustRate: true` to the config file, check the example in [training.yaml](https://github.com/audiolabs/webMUSHRA/blob/master/configs/training.yaml) and [manual](https://github.com/audiolabs/webMUSHRA/blob/master/doc/experimenter.md).
