### ISSUE TITLE
Customizing language

### ISSUE THREAD

**Issue by lowcut80** [audiolabs/webMUSHRA#52]
Hello,

If you want to customize some words in the interface (for example, in BS. 1116, changing the describing word "annoying" to "different"), where can I do it? 

Thanks for your help in advance!

**Comment by faroit** [comment]
@lowcut80 Hi,

we have a language file that you can edit:

https://github.com/audiolabs/webMUSHRA/blob/ea47252dc5d09c7ef58c3f7c57ba8a762325278f/lib/webmushra/nls/nls.js#L61-L77

**Comment by lowcut80** [comment]
Thank you. I was using the normal version so just got the Dev version and edited the words like below, but it still doesn't work. 
Is there anything else I have to change? I tried one of the configs examples included. 

// captions BS1116

nls['en']['imperceptible'] = "Imperceptible";
nls['en']['very similar'] = "Perceptible, but very similar"; 
nls['en']['similar'] = "Similar";
nls['en']['different'] = "Different"; 
nls['en']['very different'] = "Very different";

nls['de']['imperceptible'] = "Imperceptible";
nls['de']['very similar'] = "Perceptible, but very similar"; 
nls['de']['similar'] = "Similar";
nls['de']['different'] = "Different"; 
nls['de']['very different'] = "Very different";

**Comment by lowcut80** [comment]
Just to test, I even remove the "nls.js" file, but webMUSHRA still showed everything as it was. That means "nls.js" doesn't do anything for webMUSHRA? Any help would be greatly appreciated!

**Comment by faroit** [comment]
I just tried with `bs1116_nowav.yaml`. It works fine. Check your browser language settings, maybe its not set to `en`? Also make sure you delete browser cache and really use the dev version (or rebuild with node)

<img width="498" alt="image" src="https://user-images.githubusercontent.com/72940/97070869-fe18ee80-15db-11eb-8804-5f5d3fa31077.png">

**Comment by lowcut80** [comment]
AH, it worked after deleting cache. Thank you so much!
