### ISSUE TITLE
Use of removed function get_magic_quotes()

### ISSUE THREAD

**Issue by nullpunktTUD** [audiolabs/webMUSHRA#60]
The script service/write.php uses a function called ``get_magic_quotes()`` that has been removed in PHP 8: https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

Using a fresh XAMPP install (which ships with PHP 8), the results were not written because of that.

Since magic quotes are also not supported in PHP 8, I removed the conditional sanitizing and now everything seems to work fine.

**Comment by faroit** [comment]
@nullpunktTUD thats great. can you provide a PR?

**Comment by nullpunktTUD** [comment]
Yes, I can. First time providing a PR, hope everything's correct.

**Comment by faroit** [comment]
closed by #61
