### ISSUE TITLE
Multichannel Audio Reproduction

### ISSUE THREAD

**Issue by YorgosMoiragias** [audiolabs/webMUSHRA#62]
Hi to everyone,
I am trying to play an audio file of 6 channels (5.1) (96000 KHz, 24 bit) on a MUSHRA page via MOTU 828x. Although all of the 6 speakers reproduce the signal, it is highly distorted. However, when I use 16 bits per sample the audio reproduction is fine. The sound card supports both 16 and 24 bits per sample at 96000 kHz.
Is this a problem of the webMUSHRA code and is there any idea on how it can be solved?

Thanks in advance!

**Comment by faroit** [comment]
@YorgosMoiragias this might be browser dependent. Did you try on google chrome as well as firefox or safari?

**Comment by faroit** [comment]
also have you checked the javascript console for errors? 

We do check for sample rate missmatches: https://github.com/audiolabs/webMUSHRA/blob/94415c13f50d049bbc7601fb39a856ddfd282d3b/lib/webmushra/misc/MushraValidator.js#L15-L21

**Comment by YorgosMoiragias** [comment]
Thanks for your response.
 I have tried to load my config in all the available browsers and its only Firefox that is able to load it.
No such error ("Sample rate of device and stimulus") is appeared through loading and I believe that it is not a sample rate issue ( I have tried multiple sample rates, as far as my sound card can reproduce).

**Comment by faroit** [comment]
I don't think we've ever tested 24bit files and i'm actually not sure about the browser status. 

@YorgosMoiragias can you test your files with the native html5 audio tag?

**Comment by YorgosMoiragias** [comment]
I wrote a html script like this:
<audio src="resources/audio/mono_c2_5ch.wav" controls autoplay></audio>

The same problem is appearing. This kind of clipping when multichannel audio with 24 bits per sample is reproduced. 
An interesting observation is that when the audio has only 2 channels the reproduction is just fine ! Adding more channels (even if they are zero !! ) distorts the audio .

**Comment by YorgosMoiragias** [comment]
New information

The audio is reproduced fine, if I use flac codec at 24  bit depth.  
Maybe firefox does not support wav multichannel files at 24 bit (a network-bandwidth issue? )
Another interesting observation , that maybe give an intuition into the problem, is that using a lower sampling rate (e.g. 44100 Hz) alters the distortion of the reproduced multichannel audio .

**Comment by YorgosMoiragias** [comment]
It's getting more interesting , because the 32bit float files are reproduced fine.

**Comment by faroit** [comment]
okay, then i think we can close this and add warning in the readme. converting 24bit int to 32bit float is lossless and a good workaround, you agree?

**Comment by YorgosMoiragias** [comment]
Yes indeed. Another workaround is to convert the wav files to flac, again a lossless process.
Thanks for your assistance !!
