### ISSUE TITLE
Duplicated stimuli on certain browsers

### ISSUE THREAD

**Issue by tjueterb** [audiolabs/webMUSHRA#66]
Hey guys,
 
I'm setting up webMUSHRA on a https server and ran into the following problem:

On most browsers (Firefox, Chrome, Brave, Edge) the sound stimuli get duplicated, triggering the MUSHRA validator if the duplicated stimuli exceed 12s. On Safari on mac everything works fine.

When running the same setup on my local machine (On MacOS with `php -S localhost:8000`) it works as intended on all browsers. 

Any ideas where the issue is coming from? 

[Here's my config file](https://github.com/audiolabs/webMUSHRA/files/6570962/default.yaml.zip)
The rest of the code is unmodified apart from changing the rating scale labels of the MUSHRA page.

Thanks, Tobias

**Comment by faroit** [comment]
Hi @tjueterb 

>  The rest of the code is unmodified apart from changing the rating scale labels of the MUSHRA page.

did you change the files or are these the same as in the test folder?

**Comment by tjueterb** [comment]
Hey @faroit 

> did you change the files or are these the same as in the test folder?

i changed lines 29-33 and 39-44 in the file lib/webmushra/nls/nls.js (labels of the MUSHRA rating scale)
and in line 295 in the file lib/webmushra/pages/MushraPage.js i set the initial value of the sliders from 100 to 0.

When comparing my folder with the current repo i realized that 
- I deleted the dockerfile
- I'm not using the most recent version of webMUSHRA (the version I'm using still has the get_magic_quotes_gpc() )

I assume there is something going on with php because I get different behavior on my local machine and the server. I will update the server to the current version and report back.

**Comment by tjueterb** [comment]
Updating webMUSHRA to the current version solved the problem.
