### ISSUE TITLE
Labels of Mushra Scala

### ISSUE THREAD

**Issue by simonwindtner** [audiolabs/webMUSHRA#69]
Hello, 

i have a (simply) question. 
Is it possible to change the mushra scale labels (excellent - good - fair - poor - bad) ?

thanks in advance! 
best regards
simon

**Comment by faroit** [comment]
@simonwindtner sure, just change the test strings... its available for multiple languages...

https://github.com/audiolabs/webMUSHRA/blob/99bcf206564949bcce74d9795ab36ef32e1b99cd/lib/webmushra/nls/nls.js
