### ISSUE TITLE
Dynamic Annotations

### ISSUE THREAD

**Issue by YorgosMoiragias** [audiolabs/webMUSHRA#76]
Is there a known way to use webMUSHRA, so as to take dynamic annotations by the users (for example assessing quality each  half a second for an audio track)?
Or maybye if you could provide me a starting point for me to alter the provided code?

Thanks in advace

**Comment by faroit** [comment]
i guess this could be implemented here but the framework is rather old so this might be challenging. There are other frameworks that can do temporal annotations right out of the box... maybe you have a look at:

- https://github.com/midas-research/audino
- https://github.com/abarbu/audio-annotation
-

**Comment by YorgosMoiragias** [comment]
Thank you very much!
