### ISSUE TITLE
Stimuli Length

### ISSUE THREAD

**Issue by anusfoil** [audiolabs/webMUSHRA#78]
Hi, thanks for the awesome tool! I am doing some listening experiment that uses audio stimuli of ~30s length, and received error "Duration of stimulus (reference) must not exceed 12s." when running. Is there any way to increase the limit?

**Comment by faroit** [comment]
yes, you can set `strict` to False in the mushra page config: https://github.com/audiolabs/webMUSHRA/blob/99bcf206564949bcce74d9795ab36ef32e1b99cd/doc/experimenter.md#mushra-page

this will bypass the Duration check done here: https://github.com/audiolabs/webMUSHRA/blob/a064099969e9003c0ff051d60613b05298874a29/lib/webmushra/misc/MushraValidator.js#L46-L55
