### ISSUE TITLE
Is there a way to avoid looping of audio in mushra (type)?

### ISSUE THREAD

**Issue by neerajww** [audiolabs/webMUSHRA#80]
Hey, 
I will like to play the audio only once when the "Play button" is pressed. Currently, in type mushra, it continues to play the audio in a loop. Is there a way to stop continuous loop playback? I will appreciate the help.

**Comment by faroit** [comment]
I guess you have disable looping in the code

https://github.com/audiolabs/webMUSHRA/blob/99bcf206564949bcce74d9795ab36ef32e1b99cd/lib/webmushra/audio/MushraAudioControl.js#L26

we don't have a config for this. Feel free to add a PR to add this

**Comment by neerajww** [comment]
Thank you very much! This worked.

**Comment by neerajww** [comment]
There is an issue I am facing after doing this. After end of the audio in a condition, the button stays as "Pause". I will like it to go back to "Play" (that is, after the audio has ended). I will appreciate any help for pointers to the code segment for doing this.

**Comment by neerajww** [comment]
Hey @faroit , just a gentle notification in case you have pointers for the above issue.
