### ISSUE TITLE
Continually loads, both in the online demo and on a self-hosted local php server

### ISSUE THREAD

**Issue by Nosh118** [audiolabs/webMUSHRA#81]
webMushra stays continually stuck on this screen, with PHP showing no issues
![image](https://user-images.githubusercontent.com/67752804/164279316-a16f492e-1ae1-4240-b184-62475fa2427f.png)

**Comment by faroit** [comment]
can you check the browser js console for errors?

**Comment by Nosh118** [comment]
This shows up:

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at MushraAudioControl.convolve (webMUSHRA.js:2:13070)
    at MushraAudioControl.createLowerAnchor35 (webMUSHRA.js:2:3001)
    at new MushraAudioControl (webMUSHRA.js:1:1315)
    at MushraPage.init (webMUSHRA.js:4:8969)
    at PageManager.start (webMUSHRA.js:2:22994)
    at callbackFilesLoaded (startup.min.js:1:146)
    at Object.<anonymous> (webMUSHRA.js:1:18396)

**Comment by faroit** [comment]
probably a yaml error, did you modify any config?

**Comment by Nosh118** [comment]
Haven’t touched anything, this is just running the release for the first time stock

**Comment by Nosh118** [comment]
Any idea @faroit?

**Comment by faroit** [comment]
What php version do you use?

**Comment by Nosh118** [comment]
Sorted it out by using another machine! All working now except I'm getting this error when trying to submit the results:
`POST /service/write.php - Uncaught Error: Call to undefined function get_magic_quotes_gpc() in \webMUSHRA-1.4.3\service\write.php:21
Stack trace:
#0 {main}
  thrown in \webMUSHRA-1.4.3\service\write.php on line 21`
@faroit - thanks in advance

**Comment by Nosh118** [comment]
Solved the issue, I had to downgrade to PHP version 7.4.0 as get_magic_quotes_gpc() was deprecated and removed >8.0. Now works perfectly.
