### ISSUE TITLE
Is there a way to customize the numeric range for the displayed input ratings?

### ISSUE THREAD

**Issue by neerajww** [audiolabs/webMUSHRA#83]
Hey,

I am trying to use the "type mushra" page for audio perception. Though not a common practice, I wish my slider range to go from -90 to +90 instead of the current 0 to 100, and the same to reflect in the numeric input field box. Can someone help me find the code segment to help do this. I will appreciate the help.

**Comment by faroit** [comment]
the sliders are here: 

https://github.com/audiolabs/webMUSHRA/blob/99bcf206564949bcce74d9795ab36ef32e1b99cd/lib/webmushra/pages/MushraPage.js#L295

the slider labels are here:

https://github.com/audiolabs/webMUSHRA/blob/99bcf206564949bcce74d9795ab36ef32e1b99cd/lib/webmushra/pages/MushraPage.js#L423-L437

**Comment by neerajww** [comment]
Thank you @faroit !
