### ISSUE TITLE
How to modify config files to change experiment type from MUSHRA (ITU-R BS.1534) to AB (ITU-R BS.1116)?

### ISSUE THREAD

**Issue by gniadoo** [audiolabs/webMUSHRA#90]
Hello!
Like I said in the title, I want to use webMUSHRA with AB (ITU-R BS.1116) methodology, but I can't find where I need to change config files to make that.

**Comment by faroit** [comment]
Just have a look at the config folder: https://github.com/audiolabs/webMUSHRA/blob/master/configs/AB_noloop.yaml
