### ISSUE TITLE
Possible playback issues with slow hardware?

### ISSUE THREAD

**Issue by w4iei** [audiolabs/webMUSHRA#92]
I performed an informal MUSHRA test using webMUSHRA with 19 friends/family. 2-3 participants reported hearing incredibly bad audio (cracks, pops, etc) when listening to the reference. Furthermore, others rated one of my references very poor. Most users have so issues, but it does raise some questions about the compatibility across devices. Any ideas?
Unfortunately, I don't have much more information besides reported scores.

**Comment by faroit** [comment]
@w4iei I think this is still true on mobile browsers, yes. 

Not much I can do about. I would suggest stating to users that they have to use chrome or Firefox.

**Comment by w4iei** [comment]
Ok. Noted.
