### ISSUE TITLE
Option to edit MUSHRA scale from 0-100 to 0-n

### ISSUE THREAD

**Issue by w4iei** [audiolabs/webMUSHRA#98]
I wish to change the scale from 0-100 to 0-6 when judging multiple versions of the same audio task. 0-100 introduces a false sense of granularity that doesn't always generalize clearly across participants.

**Comment by faroit** [comment]
Have a look at this issue https://github.com/audiolabs/webMUSHRA/issues/69

**Comment by w4iei** [comment]
Thanks Fabian-Robert. This is helpful but only half of the solution. I would like a radio button style slider.

**Comment by faroit** [comment]
I guess you can also change the slider step values to achieve the same. 

In any case this wouldn't be a "mushra compatible" UI so it would
Be better to keep this in a private fork.
