### ISSUE TITLE
Alternate Remote Service

### ISSUE THREAD

**Issue by josharmenta** [audiolabs/webMUSHRA#99]
For regulatory reasons I need to push the test data into a CTMS rather than use the local CSV files. We're using this in the context of a clinical trial.

I assume for that to happen I need to write a separate remote service which calls the CTMS endpoint and transmits the data to the CTMS ingestion engine?

Thanks in advance for the help! :-)

**Comment by faroit** [comment]
I think you can use https://github.com/nils-werner/pymushra for that
